### ISSUE TITLE
Update hover text for field 'ID' in Project details page

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#11]
What version of the DMPRoadmap code are you running? (e.g. v2.2.0) dmpplay august 2021

Expected behaviour: Update help text to something like: "Modifiable automatically assigned number"
- [ ]  update tooltip help text to reflect proper use of this field

Actual behaviour: ID help text is referring to a pertinent ID while it is not: "A pertinent ID as determined by the funder and/or organisation."

Steps to reproduce: Move cursor over ID field in 'project details' tab

**Comment by nicolasfranck** [comment]
TODO: toon `plan_identifier` bij ID in plan export
