### ISSUE TITLE
update question/guidance crashes when customizing templates in org_admin interface

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#17]
See https://github.com/DMPRoadmap/roadmap/issues/3038

For DMPonline.be : manually fixed, and reported to Roadmap; Keep issue to check compatibility in case of updates

**Comment by nicolasfranck** [comment]
fixed long time ago

**Comment by nicolasfranck** [comment]
..but not by upstream, yuk!
