### ISSUE TITLE
When a template contains only 1 tab, the phase name is not displayed to end users

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#20]
What version of the DMPRoadmap code are you running? (e.g. v2.2.0) dmponline.be on 5 okt 2021, v3.0.2

Expected behaviour: The admin has entered a name for the phase of the template containing the DMP questions, so this should be displayed to the end user?

Actual behaviour: When the template only contains 1 phase consisting of sections and questions, the name of the phase is omitted, and/or is indicated by 'write plan'

Steps to reproduce: check template with only 1 phase, eg Horizon Europe template of Oktober 4, 2021 via the create plan form or My dashboard in case a plan already exists; and compare with view for admins via admin>templates

**Comment by nicolasfranck** [comment]
https://github.com/DMPbelgium/roadmap/issues/63
