### ISSUE TITLE
Bug for list of plans on admin 'edit user' page

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#26]
What version of the DMPRoadmap code are you running? (e.g. v2.2.0) v3.0.2 (dmponline.be on 19/11/2021)

Expected behaviour:
On an edit user page for org or super admin, a list of plans for the user is displayed. If the list is longer than 1 page (ie more than 10 plans), it is possible to see the rest of the list by clicking 'view all' or going to 'next' or 'last' page

Actual behaviour: when clicking 'view all' nothing happens. When clicking 'next' or 'last', an empty list of plans is displayed

Steps to reproduce:

    go to admin menu
    go to list of users
    select a user with >10 plans
    click 'view all' or click 'next' or 'last' page

**Comment by laurastandaert** [comment]
cf https://github.com/DMPRoadmap/roadmap/pull/3070

**Comment by nicolasfranck** [comment]
see https://github.com/DMPRoadmap/roadmap/pull/3070
