### ISSUE TITLE
Suggested feature: improved readability of downloaded document: phase title

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#28]
What version of the DMPRoadmap code are you running? (e.g. v2.2.0) v3.0.2

Expected behaviour: New line to indicate phase that was downloaded (or move to first line)

Actual behaviour: downloaded phase is separated from title only by hyphen; not readily visible for end users

Steps to reproduce: Download a plan; in particular one with a long title
example
![image](https://user-images.githubusercontent.com/13623284/146015242-27275c4e-c562-4987-b707-21a201574152.png)

**Comment by laurastandaert** [comment]
related: https://github.com/DMPRoadmap/roadmap/issues/2251#issuecomment-973964755

**Comment by nicolasfranck** [comment]
in `config/initializers/ugent.rb` overwrite as such:

```
require "plan_exports_controller"

class PlanExportsController

  def file_name
    "plan_#{@plan.id}_phase_#{@selected_phase.id}"
  end

end
```

and maybe include `updated_at` in some format?

@laurastandaert this will result in something like `plan_123_phase_45.pdf`. Note sure if that is helpful but at least it is less annoying..

**Comment by nicolasfranck** [comment]
Is actually about the title in the export which is now "<title> - <phase title>" -> better not put phase title on the next line?

**Comment by nicolasfranck** [comment]
@laurastandaert how would you like to change this title on the pdf? If I put the phase title on a separate line, in itself it is not clear that a phase is indicated, as the line is just too close to the upper title. Making it smaller, and a lighter tone would help..
