### ISSUE TITLE
Add validation to "string" fields in order to avoid database errors

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#29]
cf https://github.com/DMPRoadmap/roadmap/issues/3068

eg: plan title max 255 char

**Comment by nicolasfranck** [comment]
TODO: add "validate" via initializer, or add input length limiter.

**Comment by nicolasfranck** [comment]
See https://github.com/DMPbelgium/roadmap/commit/73a730b030717771c07c5cb34de4bc845f69041e

**Comment by nicolasfranck** [comment]
see test.dmponline.be
