### ISSUE TITLE
Confusing institutional login options for UGent and UZ Ghent

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#32]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)** v3.0.2 dmponline.be december2021

**Expected behaviour:** Have more clear distinction between UGent and UZ Ghent. Ideally name as:
- Ghent university
- Ghent university hospital

**Actual behaviour:**
![image](https://user-images.githubusercontent.com/13623284/146756728-7d5a4b69-e085-4c74-9568-d4daa9354e1b.png)

**Steps to reproduce:** Go to login screen

**Comment by nicolasfranck** [comment]
More context about this: normally, every organisation has one or no shibboleth identifier.

```
org = Org.find_by_abbreviation("UGent")
org.identifiers.where(identifier_scheme_id: IdentifierScheme.find_by_name("shibboleth").id)
```

but for the organisation "UGent", this is not true. They share the same templates, so they
want to be under the same organisation, but they have their own shibboleth identity provider.

(something to talk about, as this has complicated stuff, and I am not sure how long this is maintainable @laurastandaert @mm449 )

The roadmap code does not validate that there should be one or none, but it is implicitly expected.
It has for example a separate "where are you from" page where you can select the shibboleth idp
but that by selecting your organisation. When you then select the organisation, it takes the first identifier it finds.

We do not use that "where are you from" page, but put all links on the front page.
Unfortunately an `Identifier` has no label attribute that we can use. For that reason if
there is only one identifier, we use the name of the organisation, and if more, we repeat
the organisation with the domain name of the identifier appended to it. 

[See code](https://github.com/DMPbelgium/roadmap/blob/master/app/views/branded/shared/_sign_in_form.html.erb)


BTW: that makes the input form https://dmponline.be/org/admin/4/admin_edit a bit dangerous. You can easily delete the idp for the uzgent.

**Comment by osstynd** [comment]
Assuming the Guidance might be different, it would only imply that two organisations want to use the same templates. This might be solved through issue 16 (https://github.com/DMPbelgium/roadmap/issues/16)
