### ISSUE TITLE
Update contact details

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#34]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)** v3.0.2 dmponline.be January 2022

**Expected behaviour:** Helpdesk information for Belnet (hosting and managing the application since 1 January 2022) is provided

**Actual behaviour:** DMP Belgium consortium contact details are mentioned

**Steps to reproduce:** See Contact-us page: https://dmponline.be/contact-us

**Comment by dirkosstyn** [comment]
Belnet is also reviewing Privacy statement and Terms of use to verify if any changes are needed.

**Comment by nicolasfranck** [comment]
See https://github.com/DMPbelgium/roadmap/commit/c265c40f81e83d0466c18fc4ed50e8e8c6887be1

If you want to update the contact-us page directly, please use https://github.com/DMPbelgium/roadmap/blob/master/app/views/branded/contact_us/contacts/new.html.erb. That is only the upper part of the page though.
