### ISSUE TITLE
Evaluate 3.0.5 and 3.0.6

### ISSUE THREAD

**Issue by nicolasfranck** [DMPbelgium/roadmap#37]

**Comment by laurastandaert** [comment]
[v3.0.5](https://github.com/DMPRoadmap/roadmap/releases/tag/v3.0.5)
Bug Fixes:
•	Fix for pagination of plans retreived using the REST API V0 [#3105](https://github.com/DMPRoadmap/roadmap/pull/3105)
•	Security vulnerability patches [#3100](https://github.com/DMPRoadmap/roadmap/pull/3100), [#3097](https://github.com/DMPRoadmap/roadmap/pull/3097), [#3093](https://github.com/DMPRoadmap/roadmap/pull/3093), [#3083](https://github.com/DMPRoadmap/roadmap/pull/3083), [#3077](https://github.com/DMPRoadmap/roadmap/pull/3077)
•	Fixed issues/inconsistencies with policies [#3099](https://github.com/DMPRoadmap/roadmap/pull/3099), [#3084](https://github.com/DMPRoadmap/roadmap/pull/3084)
•	Fix for issue downloading PDFs [#3098](https://github.com/DMPRoadmap/roadmap/pull/3098), [#3054](https://github.com/DMPRoadmap/roadmap/pull/3054), [#3049](https://github.com/DMPRoadmap/roadmap/pull/3049)

 - [ ] 	**Check compatibility with belgian export**

 - Update to the PDF coversheet to always display the creator of the DMP. Caveat: if the user's account is deleted, then the anonymized name will appear
Van <https://github.com/DMPRoadmap/roadmap/pull/3049> 
 
•	Fix for issue displaying users as collaborators on a plan after they have removed themselves [#3095](https://github.com/DMPRoadmap/roadmap/pull/3095)

 - [ ] **Check compatibility**

•	Fix for API v0 not supplying the owner email address [#3094](https://github.com/DMPRoadmap/roadmap/pull/3094)
•	Fix for bug preventing Super Admins from creating new Orgs [#3091](https://github.com/DMPRoadmap/roadmap/pull/3091)

 - [ ] **Check with Org management page**

•	Fix for issue causing deleted plans to appear in the Org Admin list of plans [#3087](https://github.com/DMPRoadmap/roadmap/pull/3087)
•	Fix for CSV downloads [#3085](https://github.com/DMPRoadmap/roadmap/pull/3085), [#3075](https://github.com/DMPRoadmap/roadmap/pull/3075)
•	Fix for pagination and search on the Admin plans page [#3069](https://github.com/DMPRoadmap/roadmap/issues/3069), [#3073](https://github.com/DMPRoadmap/roadmap/pull/3073)
•	Fix for strings that were not included in translation content [#3081](https://github.com/DMPRoadmap/roadmap/pull/3081), [#3050](https://github.com/DMPRoadmap/roadmap/pull/3050)
•	Fix for issue with contributor org logic not adhering to the restrict_orgs config flag [#3078](https://github.com/DMPRoadmap/roadmap/pull/3078), [#3060](https://github.com/DMPRoadmap/roadmap/pull/3060)
•	Fix for adding contributors [#3071](https://github.com/DMPRoadmap/roadmap/pull/3071)

 - [ ] **Check impact on modifications we have made to contributors/collaborators?**

•	Removed phone number field from contributor page [#3067](https://github.com/DMPRoadmap/roadmap/pull/3067)
•	Fixed issue with merging users [#3065](https://github.com/DMPRoadmap/roadmap/pull/3065)
•	Fixed issue with emails [#3052](https://github.com/DMPRoadmap/roadmap/pull/3052)

 - [ ] **Is this the same as we noticed during roadmap testing**?

•	Fix for users unable to see API page [#3047](https://github.com/DMPRoadmap/roadmap/pull/3047)
•	Upgraded Rubocop and updated all files accordingly [#3045](https://github.com/DMPRoadmap/roadmap/pull/3045), [#3048](https://github.com/DMPRoadmap/roadmap/pull/3048)
We have also updated most Gem and JS dependencies
 
Van <https://github.com/DMPRoadmap/roadmap/releases/> 
 
[v3.0.6](https://github.com/DMPRoadmap/roadmap/releases/tag/v3.0.6)
[Latest](https://github.com/DMPRoadmap/roadmap/releases/latest)
•	Fixes for downloading PDFs (https://github.com/DMPRoadmap/roadmap/pull/3111)
 
Van <https://github.com/DMPRoadmap/roadmap/releases/>

**Comment by nicolasfranck** [comment]
Upgrade to 3.0.6 is now on test.dmponline.be

@laurastandaert

**Comment by laurastandaert** [comment]
Issue with regard to mail content was indeed apparently addressed during roadmap update: https://github.ugent.be/Universiteitsbibliotheek/roadmap/issues/13
