### ISSUE TITLE
Update 'About'

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#39]
Text to be reviewed/provided by Belnet

Currently: https://dmponline.be/about_us

**Comment by laurastandaert** [comment]
See reviewed text

**Comment by nicolasfranck** [comment]
See https://ugentbe.sharepoint.com/:w:/t/CA20.DataStewardTeam/EWxKGNX-XYlJp7vgpCUyn4wB7HYSseGZnS4uCU-m9FUYIQ

**Comment by nicolasfranck** [comment]
See https://github.com/DMPbelgium/roadmap/commit/0752032de5fc59d6a65030f508abc3704d0d8932
