### ISSUE TITLE
 RDA answer format, browse standards does not list standards

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#4]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)** dmpplay, v3.0.2

**Expected behaviour:** RDA metadata standards available in dropdown, for question that has 'RDA Metadata Standard' as answer format

**Actual behaviour:** RDA metadata standards not listed? empty 'browse standards'
![image](https://user-images.githubusercontent.com/13623284/145979423-2aea0ecc-d1a8-4a85-8a93-4b71c6e7d331.png)

**Steps to reproduce:** Select 'Test template' of Ghent University and answer question 1 of section 1 of Test phase 1. eg: https://dmpplay.dmponline.be/plans/63310/edit?phase_id=4491

**Comment by laurastandaert** [comment]
Some CORS related problem. See https://github.com/DMPRoadmap/roadmap/pull/2837#issuecomment-820284949

There seems to be a main rda rest api, but according to their github repo https://github.com/rd-alliance/metadata-catalog-v2 you can setup your own instance. Not sure if that within our scope.
-> for an answer from roadmap developers, see https://github.com/DMPRoadmap/roadmap/pull/2837#issuecomment-872327500

So apparently no one seems to care about this new question type?
Indeed, DCC widely advertised this feature when they upgraded to dmproadmap a few years ago. But so far I have failed to find an example of a template with this question type in the DCC instance, and the same seems to be true for the UC3 instance (briri stated: "We did not have anyone using the template question type for the RDA metadata standard"). So let's wait.

**Comment by TheLisaVL** [comment]
works differently in Research Outputs, issue no longer relevant
