### ISSUE TITLE
Missing GDPR and DPIA phase for Belspo Brain template

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#46]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)** 3.0.6 dmponline.be 20/04/2022

**Expected behaviour:** All funder templates have a stub GDPR record and DPIA phase to allow institutions to add GDPR related questions.
See other funder templates for expected content. 

**Actual behaviour:** No GDPR or DPIA phase foreseen, and this cannot be added through customization. Only new sections and questions can be added

**Steps to reproduce:** Select Belspo Brain DMP template

**Comment by TheLisaVL** [comment]
Added GDPR & DPIA phases to the BRAIN 2.0 template on both preview & production
