### ISSUE TITLE
Unable to Login with ORCID

### ISSUE THREAD

**Issue by ibeheydt** [DMPbelgium/roadmap#47]
I receive the following error when logging in:
Error: Unable to login with orcid: try setting the visibility of your email address to "everyone" or "trusted parties" ([orcid profile](https://orcid.org/account)). Do not forget to add this website to your "Trusted Organisations" if you're choosing for "trusted parties"

everything is correctly set in my ORCID account. can someone please help me??

**Comment by dirkosstyn** [comment]
Hello,

There is some tricky part in ORCID to enable visibility to trusted parties. Mainly the fact that this has to be enabled in 2 places.

-          Visibility options in your profile

-          Visibility options for your e-mail
The second part (e-mail settings) is crucial but somehow well hidden….

More info can also be found here: https://belnet.be/en/services-identity-mobility-federation-dmponlinebe/dmponlinebe-technical-faq (“How to connect via ORCID”):

  1.  Create your ORCID ID on ORCID Sign in<https://orcid.org/signin>
  2.  In the visibility setting options, select "everyone" or "trusted parties"
  3.  Create your password
Go to your profile in ORCID, edit e-mail settings at the bottom left. Then select “Trusted Parties”

[ORCID]


---
Dirk Osstyn
Belnet • Product Management
WTC III
Simon Bolivarlaan 30-B2 Boulevard Simon Bolivar
1000 Brussel/Bruxelles
België • Belgique
T: +32 2 790 33 33
F: +32 2 790 33 34
https://www.belnet.be
From: ibeheydt ***@***.***>
Sent: vrijdag 29 april 2022 9:19
To: DMPbelgium/roadmap ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DMPbelgium/roadmap] Unable to Login with ORCID (Issue #47)


I receive the following error when logging in:
Error: Unable to login with orcid: try setting the visibility of your email address to "everyone" or "trusted parties" (orcid profile<https://orcid.org/account>). Do not forget to add this website to your "Trusted Organisations" if you're choosing for "trusted parties"

everything is correctly set in my ORCID account. can someone please help me??
