### ISSUE TITLE
Triplicate help instructions for admins when managing templates

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#48]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)** 3.0.6 dmponline.be May 2022

**Expected behaviour:** Repetition is not necessary

**Actual behaviour:** Same text is displayed 3x when themes are associated with a question
![image](https://user-images.githubusercontent.com/13623284/166919459-e0eff09a-a0ab-4b22-a1b3-ce2ebe6c7856.png)

**Steps to reproduce:** As an admin, go to admin menu > templates and open a section with questions that have themes associated with them

**Comment by nicolasfranck** [comment]
Merged in https://github.com/DMPRoadmap/roadmap/commit/6f6dc1862e7cc325878e621092c1acb4eeb8bef8.

TODO: remove own update when merging

**Comment by laurastandaert** [comment]
I see this behaviour appear again. Was a merge not completed? @nicolasfranck
