### ISSUE TITLE
Add the owner of the plan in the overview table in 'My dashboard'

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#52]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)** v3.0.6 dmponline.be june 2022

**Expected behaviour:**
Add column 'owner' in my dashboard overview table.

use case: promoter of multiple PhD students is added as editor or co-owner to plans in the application, but has no quick way of identifying which of the plans belongs to which student. And in some cases even no possibility at all (if depending on the permission level the 'Share' tab is not available.
Example DMPopidor:
![image](https://user-images.githubusercontent.com/13623284/176204340-5c03226c-51f9-4192-9981-87095c61ba89.png)

**Actual behaviour:** no quick way of identifying which of the plans belongs to which student. And in some cases even no possibility at all (if depending on the permission level the 'Share' tab is not available.

**Steps to reproduce:** Go to dashboard view containing plans of yourself and plans that were shared with you

**Comment by nicolasfranck** [comment]
See https://github.com/DMPbelgium/roadmap/commit/6790aafc271575790d513e595d09b7519eaccb13

**Comment by nicolasfranck** [comment]
@laurastandaert see test.dmponline.be

**Comment by StCyr** [comment]
@nicolasfranck wouldn't it be a good thing to PR upstream?
