### ISSUE TITLE
DMPOnline creates an invalid .docx document

### ISSUE THREAD

**Issue by StCyr** [DMPbelgium/roadmap#58]
Please complete the following fields as applicable:

**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
https://dmponline.be

**Expected behaviour:**
MS Office can open all .docx document generated by DMPOnline

**Actual behaviour:**
The "Horizon Europe DMP+" template generates plans that cannot be exported as MS Office compatible .docx files

**Steps to reproduce:**

* On preview.dmponline.be create a plan based on the "Horizon Europe DMP" template. Save it (you don't have to change anything) and download your plan in .docx format.
* Confirm that the .docx file created cannot be opened by MS Office (2016)

**Additional information**
If you modify (a copy of) this  template and try to delete some sections, you will see that you'll need to delete them twice; It's like those sections where 2 times in the template

**Comment by TheLisaVL** [comment]
The issue seems to have been caused by the use of bullet points in the question text. When you take those out and replace them with newlines, it opens in word without issue.

**Comment by nicolasfranck** [comment]
Also happens on test.dmponline.be (more recent version). 

e.g. https://test.dmponline.be/plans/65251

**Comment by nicolasfranck** [comment]
cf. https://github.com/karnov/htmltoword/issues/73

**Comment by nicolasfranck** [comment]
apparently the ending `</strong>` is not added after the question text, but a bit further after `</ul>`. Moving that ending `</strong>` back to the end of the question text "solves" this.

**Comment by nicolasfranck** [comment]
Causes:

* question text needs to be put in "bold". For the docx export the full text is wrapped inside a `<strong>` (see https://github.com/DMPRoadmap/roadmap/blob/master/app/views/shared/export/_plan.erb#L45), as `<div class="bold">` has no effect. But the results are varying, depending on the html in the question text.

**Comment by nicolasfranck** [comment]
@laurastandaert any idea where these kind of question originate from? Question with bullet points in the question text seems like something that could be fixed just by using a select question, not?
