### ISSUE TITLE
User's school/department attribute unused

### ISSUE THREAD

**Issue by TheLisaVL** [DMPbelgium/roadmap#60]
**What version of the DMPRoadmap code are you running? (e.g. v2.2.0)**
v3.0.6

**Expected behaviour:**
Option 1: Administrators can set departments within their organisation. Users can choose their department in their profile settings.
Option 2: If not, this column in the User accounts list should be removed

**Actual behaviour:**
When listing users as an admin there is an empty column "School or Department". There is no place to edit departments as an administrator. There is no way to edit a user's department in the profile settings.

I suspect this is something forgotten in the translation between the DCC and Belgian version.

Option 1 requested by UHasselt

**Comment by TheLisaVL** [comment]
1) Currently set manually, preferable to disable it until it can be done automatically.
2) Auto: requires IDP integration (expected complexity high)

**Comment by nicolasfranck** [comment]
Path: `/org/admin/users/admin_index`
