### ISSUE TITLE
Suggested feature: include organisational templates in 'reference' view

### ISSUE THREAD

**Issue by laurastandaert** [DMPbelgium/roadmap#9]
What version of the DMPRoadmap code are you running? (e.g. v2.2.0) v3.0.2 on test.dmponline.be (june 2021)

Expected behaviour: Add institutional templates as a separate list to 'Reference>DMP templates' in top menu bar
Requested by some org admins, because easy to see templates, and start filling in template directly.
Issues to resolve:

    It would be desirable that institutional templates need to be selected by the admin to be shown across organisations there.
    Or rather that institutional templates are presented based on organisation of the user that is accessing the reference > DMP templates?
    In both cases however, this is a suggestion for future improvement that would need to be submitted to the Roadmap development team(?)

Actual behaviour: Only Funder templates are listed

Steps to reproduce: Click 'Reference' and then select 'DMP templates' in top menu bar

**Comment by laurastandaert** [comment]
Decided to remove 'create plan' from references view as temporary solution

**Comment by nicolasfranck** [comment]
Notes:

* The [/org_admin/templates/organisational](https://dmponline.be/org_admin/templates/organisational) is available, but only to an `org_admin`, and is actually meant to provide action buttons to show, edit .. of the template
* requested is to add the list of these organisational templates to the reference page for templates at  [/public_templates](https://dmponline.be/public_templates) (Reference > DMP templates)
* variable provided by the public templates controller to the ruby template is  `@templates`, which is the list of public templates. I can override that ruby template, but I need to add an **additional table**.
* when the list of public templates reaches a certain number, then the results are **divided by page** (which is not the case as there are too few). That means that url query parameters like `page`, `search`, `sort` and `sort_direction` are taken into account by the controller, but only for that one table of public templates. Adding an extra table will have to similar to the [My Dashboard](https://dmponline.be/plans) that also lists several tables (and fetches the paged results in the background)

**Comment by nicolasfranck** [comment]
Update: query parameters on public pages unused by controller?

**Comment by nicolasfranck** [comment]
See test.dmponline.be

<img width="1435" alt="Screenshot 2022-03-01 at 11 10 44" src="https://user-images.githubusercontent.com/494636/156157651-b3001756-217f-4bbb-bff2-a6de9e3a1d27.png">
